import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ModeToggle } from "@/components/modeToggle";
import { createClient } from "@/lib/supabase/server";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <nav className="w-screen flex justify-between items-center px-2 md:px-5 py-4 bg-blue-400">
          <p className="text-white text-sm md:text-base">
            Hi {user ? user.email : "Bapak/Ibu Guru"}
          </p>
          <div className="flex gap-2">
            <ModeToggle />
            <Button className="rounded-md bg-red-500 text-white">Logout</Button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
